### ISSUE TITLE
raw_trials_to_cloud fails to authenticate to google cloud

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/euctr-tracker-code#80]
The csv of the raw data scrape for Feb 2020 did not save to Google cloud storage as it usually does.

**Comment by NickCEBM** [comment]
As a note, we have manually saved a version of the February data in the meantime so it is not lost if this issue isn't fixed by the March scrape.

**Comment by madwort** [comment]
Cron emails us once a month with an error like `CommandException: You have multiple types of configured credentials (['Oauth 2.0 User Account', 'OAuth 2.0 Service Account']), which is not supported` - this is because it is still configured to use @sebbacon 's private credentials & this has not been updated. It has been run manually from Feb 2020 to current.

**Comment by madwort** [comment]
I may have just fixed this by running `gcloud auth revoke` as the cron user - as the script manually passes credentials https://github.com/ebmdatalab/euctr-tracker-code/blob/master/euctr/euctr/management/commands/raw_trials_to_cloud.py#L35

**Comment by madwort** [comment]
this worked correctly for the 2021-03-04 manual scrape
